/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;



/**
 *
 * @author gerardo
 */
public class ElegirUbicacion extends javax.swing.JFrame {
    MenuPrincipal menuPrincipal;
    public ElegirUbicacion(MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(menuPrincipal);
        FileFilter pdfFilter = new FileFilter() {
           public boolean accept(File file) {
               return file.getName().endsWith(".pdf");
           }
           public String getDescription() {
               return "Archivos PDF";
           }
        };
        fileChooser.setFileFilter(pdfFilter);
        
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fileChooser.setApproveButtonText("Guardar");
        fileChooser.setApproveButtonToolTipText("");
        fileChooser.setDialogTitle("Seleccionar ubicacion");
        fileChooser.setSelectedFile(new java.io.File("/nombre del archivo.pdf"));
        fileChooser.setToolTipText("");
        fileChooser.setName(""); // NOI18N
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        //Si se hizo click en guardar
        if (evt.paramString().contains("ApproveSelection")) {
            if (fileChooser.getSelectedFile().getAbsolutePath().endsWith(".pdf") ) {
                menuPrincipal.guardarTablaEnPdf(fileChooser.getSelectedFile().getAbsolutePath());
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El archivo deberia terminar .pdf", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } 
        //Si se hizo click en cancelar
        else {
            this.dispose();
        }       
    }//GEN-LAST:event_fileChooserActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
